# IP correspondant aux valeurs définies dans terraform/variables.tf (var.vms)
[reverse_proxy]
10.10.0.10

[app]
10.10.0.20

[database]
10.10.0.30

[all:vars]
ansible_user=cloud
ansible_python_interpreter=/usr/bin/python3
